# Porta da aplicacao
server.port=8080

# Conexao com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_b2b?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=valentim0094@gmail.com
spring.mail.password=owagyewaetwpxsgw

# Autenticacao e SSL
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.localhost=localhost

# Timeout
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Debug do SMTP
spring.mail.properties.mail.debug=true